### ISSUE TITLE
Plugin is unable to properly process when a player joins the server

### ISSUE THREAD

**Issue by XisLea** [Tonnanto/BasicQuests#30]
Whenever a person joins the server, the plugin does not create a data file for them, making them unable to receive any sort of quest. The server is using 1.20.6 Paper. In the server console, this is what shows up whenever a player joins;

`[08:41:45 ERROR]: Could not pass event PlayerJoinEvent to BasicQuests v0.5
java.lang.NoClassDefFoundError: Could not initialize class de.stamme.basicquests.lib.fastboard.FastBoard
        at BasicQuests-0.5.jar/de.stamme.basicquests.util.QuestsScoreBoardManager.getBoardForPlayer(QuestsScoreBoardManager.java:22) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.util.QuestsScoreBoardManager.show(QuestsScoreBoardManager.java:38) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.util.QuestsScoreBoardManager.refresh(QuestsScoreBoardManager.java:83) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.model.QuestPlayer.resetQuests(QuestPlayer.java:93) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.model.QuestPlayer.<init>(QuestPlayer.java:54) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:23) ~[BasicQuests-0.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:git-Paper-71]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:git-Paper-71]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:git-Paper-71]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1517) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1494) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1417) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1609) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1237) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-71]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at BasicQuests-0.5.jar/de.stamme.basicquests.lib.fastboard.FastBoardBase.<clinit>(FastBoardBase.java:183) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.util.QuestsScoreBoardManager.getBoardForPlayer(QuestsScoreBoardManager.java:22) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.util.QuestsScoreBoardManager.show(QuestsScoreBoardManager.java:38) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.util.QuestsScoreBoardManager.refresh(QuestsScoreBoardManager.java:83) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.model.QuestPlayer.resetQuests(QuestPlayer.java:93) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.model.QuestPlayer.<init>(QuestPlayer.java:54) ~[BasicQuests-0.5.jar:?]
        at BasicQuests-0.5.jar/de.stamme.basicquests.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:23) ~[BasicQuests-0.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:git-Paper-71]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:git-Paper-71]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:git-Paper-71]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1517) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1494) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1417) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1383) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1244) ~[paper-1.20.6.jar:git-Paper-71]
        ... 2 more`

**Comment by Tonnanto** [comment]
Thank you for your feedback! I will make sure to look at this  in the next patch.

For now you can disable the scoreboard in the config file which should stop the issue from happening.
To achieve this set the `disable-scoreboard` value to true in the `config.yml` like so:
```yml
# disable the inbuilt scoreboard (/quests scoreboard)
# should only be set to true if the scoreboard does not work correctly because of another plugin using it.
# quests can always be displayed on custom scoreboards using the PlaceholderAPI.
disable-scoreboard: true
```

Hope this helps! Let me know if this temporary fix works for you :)

**Comment by Youngishorange** [comment]
Can u update this for 1.21.10
